services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: 1010
    depends_on:
      - db

  php-app:
    build: .
    container_name: dbms_php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=docker

  db:
    image: mysql:8.0
    container_name: dbms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1010
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1010
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
